export const CATEGORIES = [
  { id: 'all', name: 'All', icon: '🌟' },
  { id: 'coffee', name: 'Coffee', icon: '☕' },
  { id: 'tea', name: 'Tea', icon: '🍵' },
  { id: 'buns', name: 'Buns', icon: '🥐' },
  { id: 'sandwiches', name: 'Sandwiches', icon: '🥪' },
  { id: 'lahmajun', name: 'Lahmajun', icon: '🍕' },
  { id: 'combos', name: 'Combos', icon: '🎁' },
];

export const FEATURED = [
  {
    id: 'f1',
    name: 'Caramel Macchiato',
    price: 22,
    image: 'https://images.unsplash.com/photo-1485808191679-5f86510681a2?auto=format&fit=crop&q=80&w=400&h=400',
    badge: 'Popular',
    description: 'Freshly brewed espresso with steamed milk and a drizzle of caramel syrup.',
    rating: 4.9,
    reviews: 1240,
    variants: [
      { id: 'regular', name: 'Regular', priceModifier: 0 },
      { id: 'large', name: 'Large', priceModifier: 4 },
    ],
    addons: [
      { id: 'extra_shot', name: 'Extra Espresso Shot', price: 5 },
      { id: 'oat_milk', name: 'Oat Milk', price: 3 },
    ],
  },
  {
    id: 'f2',
    name: 'Iced White Mocha',
    price: 24,
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&q=80&w=400&h=400',
    badge: 'New',
    description: 'Creamy white chocolate combined with espresso and milk, served over ice.',
    rating: 4.8,
    reviews: 850,
    variants: [
      { id: 'regular', name: 'Regular', priceModifier: 0 },
      { id: 'large', name: 'Large', priceModifier: 4 },
    ],
    addons: [
      { id: 'whipped_cream', name: 'Whipped Cream', price: 2 },
    ],
  },
  {
    id: 'f3',
    name: 'Pistachio Frappuccino',
    price: 26,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&q=80&w=400&h=400',
    badge: 'Seasonal',
    description: 'A blend of pistachio flavor, milk, and ice, topped with whipped cream and pistachio bits.',
    rating: 4.7,
    reviews: 620,
    variants: [
      { id: 'regular', name: 'Regular', priceModifier: 0 },
      { id: 'large', name: 'Large', priceModifier: 5 },
    ],
    addons: [
      { id: 'extra_pistachio', name: 'Extra Pistachio Bits', price: 4 },
    ],
  },
  {
    id: 'f4',
    name: 'Ceremonial Matcha Latte',
    price: 24,
    image: 'https://images.unsplash.com/photo-1536304811326-c796e9b37e81?auto=format&fit=crop&q=80&w=800&h=800',
    badge: 'Trending',
    description: 'Premium ceremonial grade matcha whisked to perfection with creamy steamed milk.',
    rating: 4.9,
    reviews: 1840,
    variants: [
      { id: 'regular', name: 'Regular', priceModifier: 0 },
      { id: 'large', name: 'Large', priceModifier: 5 },
    ],
    addons: [
      { id: 'honey', name: 'Honey', price: 2 },
      { id: 'oat_milk', name: 'Oat Milk', price: 3 },
    ],
  },
];

export const POPULAR = [
  {
    id: 'p1',
    name: 'Classic Coffee Bun',
    rating: 4.9,
    orders: '2.5k',
    price: 12,
    category: 'buns',
    image: 'https://images.unsplash.com/photo-1509365465985-25d11c17e812?auto=format&fit=crop&q=80&w=200&h=200',
    description: 'Our iconic creation â€” crispy caramelized exterior, soft buttery interior, filled with aromatic coffee cream.',
    reviews: 2847,
    variants: [
      { id: 'regular', name: 'Regular', priceModifier: 0 },
      { id: 'large', name: 'Large', priceModifier: 4 },
    ],
    addons: [
      { id: 'extra_filling', name: 'Extra Coffee Filling', price: 3 },
      { id: 'chocolate', name: 'Chocolate Drizzle', price: 2 },
    ],
  },
  {
    id: 'p2',
    name: 'Signature Latte',
    rating: 4.8,
    orders: '1.2k',
    price: 18,
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&q=80&w=200&h=200',
    description: 'Smooth espresso with perfectly steamed milk and a thin layer of foam.',
    reviews: 1520,
    variants: [
      { id: 'regular', name: 'Regular', priceModifier: 0 },
      { id: 'large', name: 'Large', priceModifier: 3 },
    ],
    addons: [
      { id: 'vanilla', name: 'Vanilla Syrup', price: 2 },
    ],
  },
  {
    id: 'p3',
    name: 'Green Tea Matcha',
    rating: 4.7,
    orders: '800',
    price: 16,
    category: 'tea',
    image: 'https://images.unsplash.com/photo-1582722872445-44c59ebc41dd?auto=format&fit=crop&q=80&w=400&h=400',
    description: 'High-quality matcha green tea whisked with hot water or milk.',
    reviews: 940,
    variants: [
      { id: 'regular', name: 'Regular', priceModifier: 0 },
      { id: 'large', name: 'Large', priceModifier: 4 },
    ],
    addons: [
      { id: 'honey', name: 'Honey', price: 1 },
    ],
  },
  {
    id: 'p4',
    name: 'Cheese Lahmajun',
    rating: 4.9,
    orders: '1.5k',
    price: 22,
    category: 'lahmajun',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=200&h=200',
    description: 'Traditional thin dough topped with a blend of premium cheeses and herbs.',
    reviews: 1100,
    variants: [
      { id: 'regular', name: 'Regular', priceModifier: 0 },
    ],
    addons: [
      { id: 'extra_cheese', name: 'Extra Cheese', price: 5 },
    ],
  },
  {
    id: 'p5',
    name: 'Chocolate Croissant',
    rating: 4.8,
    orders: '3.1k',
    price: 14,
    category: 'buns',
    image: 'https://images.unsplash.com/photo-1530610476181-d83430b64dcd?auto=format&fit=crop&q=80&w=200&h=200',
    description: 'Flaky, buttery croissant filled with rich dark chocolate.',
    reviews: 2100,
    variants: [
      { id: 'regular', name: 'Regular', priceModifier: 0 },
    ],
    addons: [],
  },
  {
    id: 'p6',
    name: 'Caramel Frappuccino',
    rating: 4.9,
    orders: '4.2k',
    price: 24,
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&q=80&w=200&h=200',
    description: 'Blended coffee, milk, and ice with caramel syrup, topped with whipped cream.',
    reviews: 3500,
    variants: [
      { id: 'regular', name: 'Regular', priceModifier: 0 },
      { id: 'large', name: 'Large', priceModifier: 5 },
    ],
    addons: [],
  },
  {
    id: 'p7',
    name: 'Turkey & Cheese Sandwich',
    rating: 4.6,
    orders: '950',
    price: 28,
    category: 'sandwiches',
    image: 'https://images.unsplash.com/photo-1521390188846-e2a3a97453a0?auto=format&fit=crop&q=80&w=200&h=200',
    description: 'Smoked turkey breast with melted cheese and fresh greens on artisanal bread.',
    reviews: 720,
    variants: [
      { id: 'regular', name: 'Regular', priceModifier: 0 },
    ],
    addons: [],
  },
  {
    id: 'p8',
    name: 'Blueberry Muffin',
    rating: 4.7,
    orders: '1.8k',
    price: 15,
    category: 'buns',
    image: 'https://images.unsplash.com/photo-1558401391-7899b4bd5bbf?auto=format&fit=crop&q=80&w=200&h=200',
    description: 'Moist muffin packed with fresh blueberries and topped with a sugar crumble.',
    reviews: 1400,
    variants: [
      { id: 'regular', name: 'Regular', priceModifier: 0 },
    ],
    addons: [],
  },
  {
    id: 'p9',
    name: 'Iced Peach Green Tea',
    rating: 4.8,
    orders: '2.1k',
    price: 19,
    category: 'tea',
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&q=80&w=200&h=200',
    description: 'Refreshing green tea with peach syrup and ice.',
    reviews: 1800,
    variants: [
      { id: 'regular', name: 'Regular', priceModifier: 0 },
      { id: 'large', name: 'Large', priceModifier: 4 },
    ],
    addons: [],
  },
  {
    id: 'p10',
    name: 'Iced Spanish Latte',
    rating: 4.9,
    orders: '3.5k',
    price: 22,
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&q=80&w=200&h=200',
    description: 'Sweetened condensed milk combined with espresso and milk over ice.',
    reviews: 2900,
    variants: [
      { id: 'regular', name: 'Regular', priceModifier: 0 },
      { id: 'large', name: 'Large', priceModifier: 4 },
    ],
    addons: [],
  },
  {
    id: 'p11',
    name: 'Double Chocolate Muffin',
    rating: 4.8,
    orders: '2.4k',
    price: 16,
    category: 'buns',
    image: 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?auto=format&fit=crop&q=80&w=200&h=200',
    description: 'Rich chocolate muffin with chocolate chips inside and out.',
    reviews: 1900,
    variants: [
      { id: 'regular', name: 'Regular', priceModifier: 0 },
    ],
    addons: [],
  },
  {
    id: 'p12',
    name: 'Halloumi Cheese Wrap',
    rating: 4.7,
    orders: '1.1k',
    price: 24,
    category: 'sandwiches',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&q=80&w=200&h=200',
    description: 'Grilled halloumi cheese with fresh vegetables in a soft wrap.',
    reviews: 850,
    variants: [
      { id: 'regular', name: 'Regular', priceModifier: 0 },
    ],
    addons: [],
  },
  {
    id: 'p13',
    name: 'Zaatar & Cheese Croissant',
    rating: 4.9,
    orders: '2.8k',
    price: 16,
    category: 'buns',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=200&h=200',
    description: 'Buttery croissant topped with zaatar and filled with cheese.',
    reviews: 2200,
    variants: [
      { id: 'regular', name: 'Regular', priceModifier: 0 },
    ],
    addons: [],
  },
];

export const ALL_PRODUCTS = [...FEATURED, ...POPULAR];
